spring:
  profiles:
    active: dev
    include:
      - jwt
      - mail
      - filter

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.springframework.boot.autoconfigure.security: ERROR