spring:
  profiles:
    active: dev
    include:
      - db

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework.boot.autoconfigure.security: ERROR